CREATE TABLESPACE TS_EMASA 
   DATAFILE 'ts_emasa.dbf' 
   SIZE 100M 
   AUTOEXTEND ON NEXT 200K 
   MAXSIZE 200M; 
   
CREATE USER EMASA 
    IDENTIFIED BY emasa 
    DEFAULT TABLESPACE TS_EMASA;
    
GRANT CONNECT, RESOURCE TO EMASA;
